version: '2.0'
services: 
    node-30:
        image: zary/scalable-app
        environment:
            - EPOCHS=30
        ports:
            - "8081:8080"
    node-50:
        image: zary/scalable-app
        environment:
            - EPOCHS=50
        ports:
            - "8082:8080"       