version: '2.0'
services: 
    node-30:
        image: zary/scalable-app
        build: .
        environment:
            - EPOCHS=30
        ports:
            - "8081:8080"
    node-50:
        build: .
        image: zary/scalable-app
        environment:
            - EPOCHS=50
        ports:
            - "8082:8080"
    nginx-loadbalance:
        image: load-balance-nginx
        build: 
            context: ./nginx-docker
            dockerfile: Dockerfile
        ports:
            - "8080:80"